# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: I'm a developer
email: contact@cbenz.org
description: >
  My blog!
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://blog.cbenz.org" # the base hostname & protocol for your site
twitter_username: ChristopheBenz
github_username: cbenz
repository_url: https://github.com/cbenz/blog

# Build settings
markdown: kramdown

tachyons_version: 4.6.2
